ALTER TABLE "AiSetting"
ADD COLUMN IF NOT EXISTS "schedulingPreviewTransport" TEXT NOT NULL DEFAULT 'hybrid',
ADD COLUMN IF NOT EXISTS "schedulingPreviewRetryCount" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "schedulingPreviewPollIntervalMs" INTEGER NOT NULL DEFAULT 4000,
ADD COLUMN IF NOT EXISTS "schedulingAsyncRangeDays" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN IF NOT EXISTS "schedulingAsyncManualSelections" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN IF NOT EXISTS "schedulingAsyncWithoutEvent" BOOLEAN NOT NULL DEFAULT true;
